name: Run tests

on:
  push:
    branches:
      - main
      - poc
  pull_request:
    branches:
      - main
      - poc

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        id: test
        uses: fedora-python/tox-github-action@master
        with:
          tox_env: ${{ matrix.tox_env }}
          python-version: ${{ matrix.python-version }}
    strategy:
      matrix:
        tox_env: [ py38, py39, py310 ]

  lint:
    runs-on: ubuntu-latest
    name: flake8
    steps:
      - uses: actions/checkout@v2
      - name: Run flake8
        id: flake8
        uses: fedora-python/tox-github-action@master
        with:
          tox_env: flake8
          python-version: py38
